from django.urls import path

from .views import (
    AirplaneCreateView,
    AirplaneDeleteView,
    AirplaneListView,
    AirplaneUpdateView,
    AirportCreateView,
    AirportDeleteView,
    AirportListView,
    AirportUpdateView,
    BookingCreateView,
    BookingManageCreateView,
    BookingManageDeleteView,
    BookingManageListView,
    BookingManageUpdateView,
    FlightDetailView,
    FlightListView,
    FlightManageCreateView,
    FlightManageDeleteView,
    FlightManageListView,
    FlightManageUpdateView,
    HomeView,
    PassengerCreateView,
    PassengerDeleteView,
    PassengerListView,
    PassengerUpdateView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("flights/", FlightListView.as_view(), name="flight-list"),
    path("flights/<int:pk>/", FlightDetailView.as_view(), name="flight-detail"),
    path("flights/<int:flight_id>/book/", BookingCreateView.as_view(), name="booking-create"),
    path("manage/airplanes/", AirplaneListView.as_view(), name="airplane-list"),
    path("manage/airplanes/add/", AirplaneCreateView.as_view(), name="airplane-create"),
    path("manage/airplanes/<int:pk>/edit/", AirplaneUpdateView.as_view(), name="airplane-update"),
    path("manage/airplanes/<int:pk>/delete/", AirplaneDeleteView.as_view(), name="airplane-delete"),
    path("manage/airports/", AirportListView.as_view(), name="airport-list"),
    path("manage/airports/add/", AirportCreateView.as_view(), name="airport-create"),
    path("manage/airports/<int:pk>/edit/", AirportUpdateView.as_view(), name="airport-update"),
    path("manage/airports/<int:pk>/delete/", AirportDeleteView.as_view(), name="airport-delete"),
    path("manage/flights/", FlightManageListView.as_view(), name="flight-manage-list"),
    path("manage/flights/add/", FlightManageCreateView.as_view(), name="flight-manage-create"),
    path("manage/flights/<int:pk>/edit/", FlightManageUpdateView.as_view(), name="flight-manage-update"),
    path("manage/flights/<int:pk>/delete/", FlightManageDeleteView.as_view(), name="flight-manage-delete"),
    path("manage/passengers/", PassengerListView.as_view(), name="passenger-list"),
    path("manage/passengers/add/", PassengerCreateView.as_view(), name="passenger-create"),
    path("manage/passengers/<int:pk>/edit/", PassengerUpdateView.as_view(), name="passenger-update"),
    path("manage/passengers/<int:pk>/delete/", PassengerDeleteView.as_view(), name="passenger-delete"),
    path("manage/bookings/", BookingManageListView.as_view(), name="booking-manage-list"),
    path("manage/bookings/add/", BookingManageCreateView.as_view(), name="booking-manage-create"),
    path("manage/bookings/<int:pk>/edit/", BookingManageUpdateView.as_view(), name="booking-manage-update"),
    path("manage/bookings/<int:pk>/delete/", BookingManageDeleteView.as_view(), name="booking-manage-delete"),
]
